# Generated by Django 4.2.3 on 2023-07-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
                ('number', models.CharField(max_length=15)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=100)),
                ('guest_count', models.IntegerField(max_length=1000)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
